// <auto-generated />
namespace Projet_Jdr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AjoutEntityToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjoutEntityToken));
        
        string IMigrationMetadata.Id
        {
            get { return "202112161325046_AjoutEntityToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
